# REVIEW: Array-based programming with NumPy

NumPy is a fast, powerful, and versatile library for working with multi-dimensional arrays. Implemented in C, it provides rich array-related functions at top speed. Many of its features such as vectorization, indexing, and broadcasting have become the de-facto standards of array computing and have been adopted by other libraries including deep learning libraries such as Tensorflow and Pytorch. 

Let's import it.

In [1]:
import numpy as np

## Creating simple one-dimensional arrays
We can create arrays from scratch. Here are two simple arrays: an integer array and a float array.

In [2]:
iarr = np.array([1, 3, 5, 7, 9, 11])
farr = np.array([0.00, 0.05, 0.10, 0.15, 0.20, 0.25, 0.30, 0.35])

print(iarr)
print(farr)

[ 1  3  5  7  9 11]
[0.   0.05 0.1  0.15 0.2  0.25 0.3  0.35]


We can also create an array whose elements are all zeros, ones, any other values.

In [3]:
all_zeros = np.zeros((10,))
all_ones = np.ones((12,))
ten_nines = np.full((5,), 9)

print(all_zeros, all_ones, ten_nines)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] [9 9 9 9 9]


## Displaying array attributes
These arrays have certain attributes. Here is the type of these array objects.

In [4]:
type(iarr)

numpy.ndarray

In [5]:
type(farr)

numpy.ndarray

Both of these objects are of the Numpy `ndarray` type: the fundamental data structure in NumPy. What about the elements of a NumPy array? What type are they? We can use the `dtype` attribute to find that out.

In [6]:
iarr.dtype

dtype('int64')

In [7]:
farr.dtype

dtype('float64')

Similarly, how many elements are in each array?

In [8]:
iarr.size, farr.size

(6, 8)

You can also display the number of elements in an array using Python's `len` function:

In [9]:
len(iarr), len(farr)

(6, 8)

We can also use the `ndim` attribute to find what the number of dimensions an array has. This is also called the rank of the array. As we know, both of the above arrays are one-dimensional (1D).

In [10]:
iarr.ndim, farr.ndim

(1, 1)

Finally, we can get the shapes of these arrays: how many elements in each dimension.

In [11]:
iarr.shape

(6,)

In [12]:
farr.shape

(8,)

## Reshaping arrays
We can reshape these one-dimensional arrays into multi-dimensional arrays. For example, let's create a new 2D array with 3 rows and 2 columns by by reshaping `iarr`. 

In [13]:
i2d = iarr.reshape(3, 2)

Here are the number of dimensions and shape of this new 2D array.

In [14]:
print(i2d.ndim)
print(i2d.shape)

2
(3, 2)


Similarly, let's create a new 3D array (an array of 2D arrays) by reshaping `farr` into a 3D array with two elements in every dimension.

In [15]:
f3d = farr.reshape(2,2,2)

Notice that `reshape` does not affect the `farr` array per say; it uses it to create a new array with the requested dimensions. Here are the number of dimensions and shape of this now 3D array.

In [16]:
print(f3d.ndim)
print(f3d.shape)

3
(2, 2, 2)


## Creating multi-dimensional arrays
We can also create multi-dimensional arrays from scratch. Keep in mind that a 2D array is an array of 1D arrays. And a 3D array is an array of 2D arrays, and so on. Here is a 2D array made of two 1D arrays: one with 10 zeros and another with 10 ones. Each 1D array becomes a row in the new 2D array.

In [17]:
f2d = np.array([np.zeros(10), np.ones(10)])

print(f2d)
print("ndim: ", f2d.ndim)
print("shape: ", f2d.shape)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
ndim:  2
shape:  (2, 10)


Let's create a 3D array that is an array of 3 2D arrays

In [18]:
f3d = np.array([f2d, f2d, f2d])

print(f3d)
print("ndim: ", f3d.ndim)
print("shape: ", f3d.shape)

[[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]]
ndim:  3
shape:  (3, 2, 10)


We can also use the `full` function to create an array of any dimensions (the first argument) populated with a given value (the second argument). 

In [19]:
i1d = np.full(4, 7)
i2d = np.full((5,7), 3)
i3d = np.full((3, 2, 7), 9)

print("\nID array:\n", i1d)
print("\n2D array:\n", i2d)
print("\n3D array:\n", i3d) 


ID array:
 [7 7 7 7]

2D array:
 [[3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3]]

3D array:
 [[[9 9 9 9 9 9 9]
  [9 9 9 9 9 9 9]]

 [[9 9 9 9 9 9 9]
  [9 9 9 9 9 9 9]]

 [[9 9 9 9 9 9 9]
  [9 9 9 9 9 9 9]]]


## Creating arrays using ranges
Arrays can also be created from ranges. Here is an array with elements from 0-101 (exclusive; 0 up to 101 but not including 101) range.

In [20]:
np.arange(101)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

Here is an array with elements ranging from 3(inclusive) to 13 (exclusive)

In [21]:
nums = np.arange(3, 13)

print(nums)

[ 3  4  5  6  7  8  9 10 11 12]


Here is another array with all the numbers between 3 and 100 that are multiple of 3.

In [22]:
np.arange(3, 100, step=3)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

Sometimes you want to take a closed interval $[a,b]$ and generate $n$ equally separated numbers within that interval. We use the `np.linspace` function for that. For example, here are 9 numbers equally spaced within the interval $[2,4]$ including 2 and 4.

In [23]:
np.linspace(2, 4, num=9)

array([2.  , 2.25, 2.5 , 2.75, 3.  , 3.25, 3.5 , 3.75, 4.  ])

And if we want to fill the array with a range of values, use the `np.arange` or `np.linespace` functions as the second argument. 

In [24]:
i1d = np.full(4, np.arange(4))
i2d = np.full((5,7), np.arange(7))
i3d = np.full((3, 2, 9), np.linspace(3, 4, num=9))

print("\nID array:\n", i1d)
print("\n2D array:\n", i2d)
print("\n3D array:\n", i3d)


ID array:
 [0 1 2 3]

2D array:
 [[0 1 2 3 4 5 6]
 [0 1 2 3 4 5 6]
 [0 1 2 3 4 5 6]
 [0 1 2 3 4 5 6]
 [0 1 2 3 4 5 6]]

3D array:
 [[[3.    3.125 3.25  3.375 3.5   3.625 3.75  3.875 4.   ]
  [3.    3.125 3.25  3.375 3.5   3.625 3.75  3.875 4.   ]]

 [[3.    3.125 3.25  3.375 3.5   3.625 3.75  3.875 4.   ]
  [3.    3.125 3.25  3.375 3.5   3.625 3.75  3.875 4.   ]]

 [[3.    3.125 3.25  3.375 3.5   3.625 3.75  3.875 4.   ]
  [3.    3.125 3.25  3.375 3.5   3.625 3.75  3.875 4.   ]]]


## Generating arrays of random numbers

NumPy can also generate arrays filled with random numbers using the `np.random.randn` function. The generated numbers are sampled from a normal Gaussian distribution with 0 mean and 1 variance. Here is 2D array ($4 \times 5$):

In [25]:
np.random.randn(4,5)

array([[-0.17756847, -0.73944774,  0.19983709,  0.16338751, -0.76276818],
       [ 0.8867498 ,  0.15835683,  0.13416736, -1.03926812,  0.38031256],
       [ 1.36675744, -1.47260776,  1.7590074 ,  0.2924291 , -0.97627854],
       [-0.5206216 , -1.67201771, -1.00873104,  2.26778382,  0.73847688]])

which is equivalent to:

In [26]:
np.random.normal(size=(4, 5))

array([[ 0.98485623,  0.78667318,  0.48477825,  1.86565932,  1.41170753],
       [-1.34719274,  2.03088023, -0.0643879 , -0.52902487,  0.59083388],
       [-0.78977091, -0.73819971, -1.01519815,  0.93836508,  0.30351411],
       [-0.96348654,  1.99326427, -0.87722854,  1.06531709, -1.56650042]])

or

In [27]:
np.random.normal(loc=0, scale=1, size=(4, 5))

array([[ 1.33029432, -0.43768416, -0.28510307,  0.89632481, -0.88763532],
       [-0.69518572, -0.1039877 ,  0.6857845 ,  0.07651208, -1.51767882],
       [ 0.10899431, -0.06312371,  1.40678574, -0.83048727,  0.07852251],
       [-0.42281033, -0.26653996, -0.01196454, -0.23262615, -0.57502259]])

But if you want random integers within a given range, use `np.random.randint`. For example, the following simulates rolling a die 100 times.

In [28]:
np.random.randint(1, 7, 100)

array([6, 3, 6, 3, 4, 1, 5, 4, 6, 4, 1, 4, 1, 2, 2, 6, 2, 1, 1, 6, 2, 6,
       3, 2, 2, 1, 4, 6, 2, 4, 6, 1, 6, 1, 4, 1, 2, 1, 6, 4, 3, 4, 5, 6,
       5, 5, 4, 6, 4, 5, 2, 2, 3, 2, 5, 4, 6, 3, 3, 6, 6, 6, 4, 1, 1, 1,
       3, 3, 1, 2, 6, 1, 4, 6, 5, 3, 5, 6, 6, 3, 3, 5, 3, 5, 4, 6, 4, 2,
       6, 3, 5, 2, 4, 2, 3, 6, 2, 1, 3, 6])

A lot of times we want to be able to reproduce our randomized experiments. To so so, we need to seed a pseudo-random generator and then use it to generate random numbers. Here is an a random generator seeded with the value 17.

In [29]:
rgen = np.random.RandomState(17)

Now we can use this generator to create random arrays. Here are three random arrays: $2 \times 4 \times 3$, $3 \times 3$, and one-dimensional.

In [30]:
rgen.randint(1, 7, size=(2, 4, 3))

array([[[2, 2, 1],
        [6, 5, 5],
        [5, 2, 2],
        [2, 1, 3]],

       [[3, 4, 4],
        [4, 2, 2],
        [2, 6, 6],
        [2, 1, 6]]])

In [31]:
rgen.randn(3,3)

array([[-0.98525081, -1.05703547, -2.05153126],
       [ 1.21389446, -0.3884363 ,  1.37570986],
       [-0.07229169, -0.07374186,  0.0852946 ]])

In [32]:
rgen.normal(loc=10, scale=2, size=100)

array([ 9.65202716,  8.15966352,  8.73116601, 10.50258947, 12.44943781,
       10.17881968,  8.34026135, 10.94509223,  8.17656093,  9.70888585,
        7.98072405, 10.36662361, 10.47850307, 12.53445862, 11.84434913,
       11.00458003, 10.63107922, 10.70567988,  9.06736143, 10.67145563,
       10.689168  ,  9.83351693,  9.28495304, 11.77781781,  4.59393349,
        7.80193631,  9.95760942, 13.47938725, 13.41517309, 10.95356487,
       10.6873841 ,  9.55517877, 10.81832625,  8.4658072 ,  7.86551697,
        9.1114213 , 10.45921952, 11.70502529, 10.83455575, 12.02425194,
       11.3696746 ,  7.5998159 ,  8.74145095, 11.64588045,  8.15715242,
        9.84681331,  8.55671935, 14.47809847,  9.60828963, 10.34588629,
        8.14942385, 10.03900555, 11.14511331, 10.47095418, 10.06738514,
        9.98577212, 12.55131359, 12.00228501, 11.83816279, 11.10247757,
       11.45638389, 10.87880382,  4.80454537, 10.13676316, 10.13206777,
        8.55831996,  9.28222966,  4.50673256, 12.25536122,  9.96

## Flattening multi-dimensional arrays
We can convert a multi-dimensional array into a flat one-dimensional array using `np.flatten()` or `np.ravel()`

In [33]:
i3d.flatten()

array([3.   , 3.125, 3.25 , 3.375, 3.5  , 3.625, 3.75 , 3.875, 4.   ,
       3.   , 3.125, 3.25 , 3.375, 3.5  , 3.625, 3.75 , 3.875, 4.   ,
       3.   , 3.125, 3.25 , 3.375, 3.5  , 3.625, 3.75 , 3.875, 4.   ,
       3.   , 3.125, 3.25 , 3.375, 3.5  , 3.625, 3.75 , 3.875, 4.   ,
       3.   , 3.125, 3.25 , 3.375, 3.5  , 3.625, 3.75 , 3.875, 4.   ,
       3.   , 3.125, 3.25 , 3.375, 3.5  , 3.625, 3.75 , 3.875, 4.   ])

In [34]:
i3d.ravel()

array([3.   , 3.125, 3.25 , 3.375, 3.5  , 3.625, 3.75 , 3.875, 4.   ,
       3.   , 3.125, 3.25 , 3.375, 3.5  , 3.625, 3.75 , 3.875, 4.   ,
       3.   , 3.125, 3.25 , 3.375, 3.5  , 3.625, 3.75 , 3.875, 4.   ,
       3.   , 3.125, 3.25 , 3.375, 3.5  , 3.625, 3.75 , 3.875, 4.   ,
       3.   , 3.125, 3.25 , 3.375, 3.5  , 3.625, 3.75 , 3.875, 4.   ,
       3.   , 3.125, 3.25 , 3.375, 3.5  , 3.625, 3.75 , 3.875, 4.   ])

## Indexing and slicing
Let's start with a 2D array (4 rows by 5 columns.

In [35]:
a = np.arange(1, 100, 5).reshape(4, 5)
print(a)

[[ 1  6 11 16 21]
 [26 31 36 41 46]
 [51 56 61 66 71]
 [76 81 86 91 96]]


In [36]:
np.arange(1, 100, 5).size

20

NumPy uses zero-based indexing and gives different ways to index and/or slice arrays. It is important to get familiar and comfortable with the different ways of indexing/slicing these arrays. Let's see a few examples.

Here is the first element (row 0 and column 0):

In [37]:
a[0,0]

1

And the last element (row 3 and column 4):

In [38]:
a[3,4]

96

The whole first row:

In [39]:
a[0,:]

array([ 1,  6, 11, 16, 21])

And the last row: 

In [40]:
a[3,:]

array([76, 81, 86, 91, 96])

Here are the first three rows:

In [41]:
a[:3, :]

array([[ 1,  6, 11, 16, 21],
       [26, 31, 36, 41, 46],
       [51, 56, 61, 66, 71]])

And the last two rows:

In [42]:
a[2:, :]

array([[51, 56, 61, 66, 71],
       [76, 81, 86, 91, 96]])

Here are second and last rows - starting at row 1 and ending at row 4 (exclusive), with a step of 2.

In [43]:
a[1:4:2,:]

array([[26, 31, 36, 41, 46],
       [76, 81, 86, 91, 96]])

Here is the first column:

In [44]:
a[:,0]

array([ 1, 26, 51, 76])

And the second column: 

In [45]:
 a[:,1]

array([ 6, 31, 56, 81])

And the last column:

In [46]:
a[:,4]

array([21, 46, 71, 96])

Here are the first and last columns - starting at column 0 and ending at column 5 (exclusive) with a step of 4.

In [47]:
a[:,0:5:4]

array([[ 1, 21],
       [26, 46],
       [51, 71],
       [76, 96]])

Here are all the columns except the first two:

In [48]:
a[:, 2:]

array([[11, 16, 21],
       [36, 41, 46],
       [61, 66, 71],
       [86, 91, 96]])

And all the columns except the last three:

In [49]:
a[:, :2]

array([[ 1,  6],
       [26, 31],
       [51, 56],
       [76, 81]])

Here is the whole array:

In [50]:
a

array([[ 1,  6, 11, 16, 21],
       [26, 31, 36, 41, 46],
       [51, 56, 61, 66, 71],
       [76, 81, 86, 91, 96]])

In [51]:
a[:,:]

array([[ 1,  6, 11, 16, 21],
       [26, 31, 36, 41, 46],
       [51, 56, 61, 66, 71],
       [76, 81, 86, 91, 96]])

In [52]:
a[::,::]

array([[ 1,  6, 11, 16, 21],
       [26, 31, 36, 41, 46],
       [51, 56, 61, 66, 71],
       [76, 81, 86, 91, 96]])

Here are the middle three columns of the middle two rows:

In [53]:
a[1:3:1, 1:4:1]

array([[31, 36, 41],
       [56, 61, 66]])

## Indexing using conditional expressions
We can also use boolean array expressions to select array elements where those expressions hold. For example, here are all the odd elements in `a`:

In [54]:
a[a % 2 != 0]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

And here are only the elements that are < 50:

In [55]:
a[a < 50]

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

We can use these boolean expressions with the `np.where` to return arrays with certain properties. For example, the following keeps the odd numbers and zeros out (the last argument is 0) all the even elements in the array `a`

In [56]:
np.where(a % 2 != 0, a, 0)

array([[ 1,  0, 11,  0, 21],
       [ 0, 31,  0, 41,  0],
       [51,  0, 61,  0, 71],
       [ 0, 81,  0, 91,  0]])

Compare that to the following with the last two arguments are reversed. This reverses the logic and the elements where the conditions hold are zeroed out.

In [57]:
np.where(a % 2 != 0, 0, a)

array([[ 0,  6,  0, 16,  0],
       [26,  0, 36,  0, 46],
       [ 0, 56,  0, 66,  0],
       [76,  0, 86,  0, 96]])

Similarly, the following statement returns an array where any element with a value between 11 and 60 is replaced with -1 (the :

In [58]:
np.where(np.logical_and(a >= 11, a <= 60), -1, a)

array([[ 1,  6, -1, -1, -1],
       [-1, -1, -1, -1, -1],
       [-1, -1, 61, 66, 71],
       [76, 81, 86, 91, 96]])

The following reverses the logic.

In [59]:
np.where(np.logical_and(a >= 11, a <= 60), a, -1)

array([[-1, -1, 11, 16, 21],
       [26, 31, 36, 41, 46],
       [51, 56, -1, -1, -1],
       [-1, -1, -1, -1, -1]])

## Using fancy indexing
We can slice an array using an array of indexes. This is called **fancy indexing**. Given the array:

In [60]:
a = np.arange(1, 100).reshape(33, 3)

print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]
 [34 35 36]
 [37 38 39]
 [40 41 42]
 [43 44 45]
 [46 47 48]
 [49 50 51]
 [52 53 54]
 [55 56 57]
 [58 59 60]
 [61 62 63]
 [64 65 66]
 [67 68 69]
 [70 71 72]
 [73 74 75]
 [76 77 78]
 [79 80 81]
 [82 83 84]
 [85 86 87]
 [88 89 90]
 [91 92 93]
 [94 95 96]
 [97 98 99]]


Here is an array containing first, third and tenth rows of `a`:

In [61]:
a[[0, 2, 9]]

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [28, 29, 30]])

And here is an array containing the odd rows only of `a`:

In [62]:
a[np.arange(1,33, 2)]

array([[ 4,  5,  6],
       [10, 11, 12],
       [16, 17, 18],
       [22, 23, 24],
       [28, 29, 30],
       [34, 35, 36],
       [40, 41, 42],
       [46, 47, 48],
       [52, 53, 54],
       [58, 59, 60],
       [64, 65, 66],
       [70, 71, 72],
       [76, 77, 78],
       [82, 83, 84],
       [88, 89, 90],
       [94, 95, 96]])

## Using fancy indexing to shuffle a dataset

The above `a` array has the following shape

In [63]:
a.shape

(33, 3)

which means 33 rows and 3 columns. Let's shuffle these rows by first generating an array of 33 valid inedexes:

In [64]:
indexes = np.arange(len(a))
indexes

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

Let's suffle these indexes:

In [65]:
np.random.shuffle(indexes)
indexes

array([15,  9, 28,  3,  4, 16,  5,  1, 30, 23,  7, 10, 31, 27,  8, 11,  0,
        2, 20, 18, 19,  6, 32, 29, 12, 21, 22, 13, 25, 14, 17, 26, 24])

We can reduce the above two steps for generating and shuffling indexes into one step like this:

In [66]:
indexes = np.random.permutation(len(a))
indexes

array([15, 17,  7, 22,  9,  8, 32, 13, 27,  4,  2,  3, 14, 20,  5, 16, 30,
       18, 31, 23, 21,  6, 26,  1, 10, 19, 11, 29, 28, 25, 24, 12,  0])

We finally use fancy indexing to shuffle the rows of the `a` array:

In [67]:
new_a = a[indexes]
new_a

array([[46, 47, 48],
       [52, 53, 54],
       [22, 23, 24],
       [67, 68, 69],
       [28, 29, 30],
       [25, 26, 27],
       [97, 98, 99],
       [40, 41, 42],
       [82, 83, 84],
       [13, 14, 15],
       [ 7,  8,  9],
       [10, 11, 12],
       [43, 44, 45],
       [61, 62, 63],
       [16, 17, 18],
       [49, 50, 51],
       [91, 92, 93],
       [55, 56, 57],
       [94, 95, 96],
       [70, 71, 72],
       [64, 65, 66],
       [19, 20, 21],
       [79, 80, 81],
       [ 4,  5,  6],
       [31, 32, 33],
       [58, 59, 60],
       [34, 35, 36],
       [88, 89, 90],
       [85, 86, 87],
       [76, 77, 78],
       [73, 74, 75],
       [37, 38, 39],
       [ 1,  2,  3]])

## Splitting an array into two sets

A common task in machine learning is to split a given dataset into two or three sets. To see how that is done, we'll split the array we just shuffled in 70/30 way. First we calculate the index at which we will be splitting:

In [68]:
split_ndx = int(.7 * len(new_a))

Here is the split with the 70% of the records:

In [69]:
new_a[0:split_ndx, :]

array([[46, 47, 48],
       [52, 53, 54],
       [22, 23, 24],
       [67, 68, 69],
       [28, 29, 30],
       [25, 26, 27],
       [97, 98, 99],
       [40, 41, 42],
       [82, 83, 84],
       [13, 14, 15],
       [ 7,  8,  9],
       [10, 11, 12],
       [43, 44, 45],
       [61, 62, 63],
       [16, 17, 18],
       [49, 50, 51],
       [91, 92, 93],
       [55, 56, 57],
       [94, 95, 96],
       [70, 71, 72],
       [64, 65, 66],
       [19, 20, 21],
       [79, 80, 81]])

And here is the other 30% split:

In [70]:
new_a[split_ndx:, :]

array([[ 4,  5,  6],
       [31, 32, 33],
       [58, 59, 60],
       [34, 35, 36],
       [88, 89, 90],
       [85, 86, 87],
       [76, 77, 78],
       [73, 74, 75],
       [37, 38, 39],
       [ 1,  2,  3]])

## Sorting arrays and getting their unique values

Having an array such as the following:

In [71]:
dat = np.random.randint(1,11, 20)
dat

array([ 3,  9,  1,  1,  8,  7,  7,  8,  4,  5,  5,  9,  1,  8,  2,  8,  6,
       10,  6,  5])

We can sort this array in-place like this:

In [72]:
dat.sort()
dat

array([ 1,  1,  1,  2,  3,  4,  5,  5,  5,  6,  6,  7,  7,  8,  8,  8,  8,
        9,  9, 10])

And to get the unique values that make up this array, we write:

In [73]:
np.unique(dat)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

To get the frequency of each value, we call the `np.unique` function with the `return_counts=`.

In [74]:
unique_values, counts = np.unique(dat, return_counts=True)
unique_values, counts

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([3, 1, 1, 1, 3, 2, 2, 4, 2, 1]))

Let's display each value alogside its count:

In [75]:
np.asarray((unique_values, counts)).T

array([[ 1,  3],
       [ 2,  1],
       [ 3,  1],
       [ 4,  1],
       [ 5,  3],
       [ 6,  2],
       [ 7,  2],
       [ 8,  4],
       [ 9,  2],
       [10,  1]])

## Concatenating arrays along an axis
We can take two arrays and concatenate them along an axis. For example, given the following 2D arrays:

In [76]:
A = np.random.randint(1, 10, size=(3,3))
B = np.random.randint(11, 20, size=(3,3))
A, B

(array([[1, 7, 7],
        [1, 5, 6],
        [1, 9, 7]]),
 array([[19, 14, 14],
        [15, 16, 16],
        [17, 17, 14]]))

Here is the concatenation of `A` and `B` along the row axis (axis = 0: adding new rows)

In [77]:
np.concatenate([A, B], axis=0)

array([[ 1,  7,  7],
       [ 1,  5,  6],
       [ 1,  9,  7],
       [19, 14, 14],
       [15, 16, 16],
       [17, 17, 14]])

And here is the concatenation of `A` and `B` along the column axis (axis = 1: adding new columns)

In [78]:
np.concatenate([A, B], axis=1)

array([[ 1,  7,  7, 19, 14, 14],
       [ 1,  5,  6, 15, 16, 16],
       [ 1,  9,  7, 17, 17, 14]])

## Peforming array arithmetic
Given two arrays of the same shape, we can perform element-wise arithmetic operations on these arrays. 

Let arrays `a` and `b` be the following:

In [79]:
a = np.arange(1, 19, 2).reshape(3,3)
b = np.arange(2, 19, 2).reshape(3,3)

In [80]:
a

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [81]:
b

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

We can perform the following element-by-element arithmetic and logical operations without any loops.

In [82]:
a + b

array([[ 3,  7, 11],
       [15, 19, 23],
       [27, 31, 35]])

In [83]:
a - b

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1]])

In [84]:
a * b

array([[  2,  12,  30],
       [ 56,  90, 132],
       [182, 240, 306]])

In [85]:
a / b

array([[0.5       , 0.75      , 0.83333333],
       [0.875     , 0.9       , 0.91666667],
       [0.92857143, 0.9375    , 0.94444444]])

In [86]:
b % a

array([[0, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [87]:
a < b

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [88]:
b < a

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

## Peforming matrix operations
Say that we have the following matrices:

$ A = \begin{bmatrix} 1 & 2 & 1 \\ 3 & 0 & 1 \\ 0 & 2 & 4 \end{bmatrix}$

$$ B = \begin{bmatrix} 3 & 1 & 2 \\ 1 & 1 & 0 \\ 1 & 3 & 1 \end{bmatrix}$$

$$ v = \begin{bmatrix} 1 \\ 3  \\ 2  \end{bmatrix} $$

We can represent them using three Numpy arrays as follows:

In [89]:
A = np.array([[1,2,1], [3, 0, 1], [0, 2, 4]])
B= np.array([3, 1, 2, 1, 1, 0, 1, 3, 1]).reshape(3,3)
v = np.array([1, 3, 2]).reshape(3,1)

print("A = \n", A)
print("B = \n", B)
print("v = \n", v)

A = 
 [[1 2 1]
 [3 0 1]
 [0 2 4]]
B = 
 [[3 1 2]
 [1 1 0]
 [1 3 1]]
v = 
 [[1]
 [3]
 [2]]


Now can perform the matrix operations we know from linear algebra. Here are a few example matrix operations. 

$A + B$:

In [90]:
A + B

array([[4, 3, 3],
       [4, 1, 1],
       [1, 5, 5]])

$3B$:

In [91]:
3 * B

array([[9, 3, 6],
       [3, 3, 0],
       [3, 9, 3]])

$A - 3B$:

In [92]:
A - 3 * B

array([[-8, -1, -5],
       [ 0, -3,  1],
       [-3, -7,  1]])

$A \times B$:

In [93]:
A.dot(B)

array([[ 6,  6,  3],
       [10,  6,  7],
       [ 6, 14,  4]])

or using the `@` matrix multiplication operator which is the same as calling `np.matmul`:

In [94]:
A @ B 

array([[ 6,  6,  3],
       [10,  6,  7],
       [ 6, 14,  4]])

which is not the same as $B \times A$:

In [95]:
B.dot(A)

array([[ 6, 10, 12],
       [ 4,  2,  2],
       [10,  4,  8]])

or

In [96]:
B @ A

array([[ 6, 10, 12],
       [ 4,  2,  2],
       [10,  4,  8]])

And here is the determinant of $A$ which is denoted by $|A|$:

In [97]:
np.linalg.det(A)

-19.999999999999996

The transpose of $B$ which is denoted as $B^T$:

In [98]:
B.T

array([[3, 1, 1],
       [1, 1, 3],
       [2, 0, 1]])

Notice that $v \times A$ is not valid because of their dimension misalignment. Uncomment the statement below to see the error

In [99]:
# v.dot(A)

However, $A \times v$ is valid:

In [100]:
A.dot(v)

array([[ 9],
       [ 5],
       [14]])

And so is  $v^T \times A$:

In [101]:
v.T.dot(A)

array([[10,  6, 12]])

Finally we can calculate the inverse matrix of $A$ denoted as $A^{-1}$:

In [102]:
Ainv = np.linalg.inv(A)

which we can verify by calculating $A \times A^{-1}$.

In [103]:
A.dot(np.linalg.inv(A)).round()

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [-0.,  0.,  1.]])

which should be the same as the identity matrix $I$.

In [104]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Using universal element-wise functions
Given the array $A$:

In [105]:
A

array([[1, 2, 1],
       [3, 0, 1],
       [0, 2, 4]])

We can calculate the square root, absolute value, sin, cos, etc of its elements.

In [106]:
np.sqrt(A)

array([[1.        , 1.41421356, 1.        ],
       [1.73205081, 0.        , 1.        ],
       [0.        , 1.41421356, 2.        ]])

In [107]:
np.abs(A)

array([[1, 2, 1],
       [3, 0, 1],
       [0, 2, 4]])

In [108]:
np.sin(A)

array([[ 0.84147098,  0.90929743,  0.84147098],
       [ 0.14112001,  0.        ,  0.84147098],
       [ 0.        ,  0.90929743, -0.7568025 ]])

In [109]:
np.exp(A)

array([[ 2.71828183,  7.3890561 ,  2.71828183],
       [20.08553692,  1.        ,  2.71828183],
       [ 1.        ,  7.3890561 , 54.59815003]])

## Calling statistical functions
NumPy also comes with functions for summarizing arrays. Here are some examples:

In [110]:
A

array([[1, 2, 1],
       [3, 0, 1],
       [0, 2, 4]])

In [111]:
np.max(A)

4

In [112]:
A.max()

4

In [113]:
np.min(A)

0

In [114]:
A.min()

0

In [115]:
np.sum(A)

14

In [116]:
A.sum()

14

In [117]:
np.cumsum(A)   # Cummulative sum

array([ 1,  3,  4,  7,  7,  8,  8, 10, 14])

In [118]:
A.cumsum()     # Cummulative sum

array([ 1,  3,  4,  7,  7,  8,  8, 10, 14])

In [119]:
np.mean(A)     # average

1.5555555555555556

In [120]:
A.mean()       # average

1.5555555555555556

In [121]:
np.var(A)      # variance

1.5802469135802468

In [122]:
A.var()        # variance

1.5802469135802468

In [123]:
np.median(A)   # median

1.0